apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    worker_processes 1;

    events {
        worker_connections 1024;
    }

    http {
        upstream mainAppServer {
            server app-service:3000; #K8S main app service DNS
        }

        server {
            listen 80;
            server_name localhost;

            location / {
                proxy_pass http://mainAppServer;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
        }
    }


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-app
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/ # MOUNT
          readOnly: true
          name: nginx-volume
      volumes:
      - name: nginx-volume
        configMap:
          name: nginx-config # NGINX CONFIG MAP DECLARED BEFORE
          items:
          - key: nginx.conf
            path: nginx.conf

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx-service
spec:
  type: LoadBalancer # IT GENERATES AN EXTERNAL IP TO DISTRIBUTE THE BALANCE BETWEEN THE MAIN APP CONTAINERS
  selector:
    app: nginx-app
  ports:
  - port: 80