version: '3'

services:
  node-rest-api-dev:
    image: node:latest
    build:
      dockerfile: DockerfileDev
      context: .
    ports:
      - 3000:3000
    volumes:
      - .:/app/
    depends_on:
    - mysql-app
  mysql-app:
    image: mysql:latest
    ports:
      - 3306
    volumes:
      - .docker/mysql/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=dbdev123