apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    name: app-config
data:
  env: |
    DB_NAME=ecommerce
    DB_PORT=3306
    DB_USERNAME=root
    DB_HOST=mysql-service
    APP_PORT=3000
