apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app-service
spec:
  type: NodePort
  selector:
    app: app # MAIN APPLICATION NAME
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000